# Generated by Django 5.0.3 on 2024-03-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0023_alter_product_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'permissions': [('cancel_product_publication', 'Отмена публикации продукта'), ('change_product_description', 'Изменение описания продукта'), ('change_product_category', 'Изменение категории продукта')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
